### ISSUE TITLE
Position library refactor

### ISSUE THREAD

**Issue by mesozoic-technology** [overlay-market/v0-core#18]
The position library is slightly redundant as currently written. 

For instance in a call to unwind, we are finding the open interest on a position then later finding the notional value of a position, which performs an internal call finding the open interest. 

In liquidate, a call is made to see if it can be liquidated, followed by a call to find out the open interest -- the latter can return the former.

**Comment by mesozoic-technology** [comment]
This library should be stripped down to the most basic functions required for our contract, but we should make a new contract with the position libraries current functions to be employed as a viewing contract that our frontend can use to see important data regarding various positions from any supported market

**Comment by mikeyrf** [comment]
This makes sense to me 👍
