### ISSUE TITLE
Separate out compoundPeriod from updatePeriod

### ISSUE THREAD

**Issue by mikeyrf** [overlay-market/v0-core#24]
Consider adding a new parameter `compoundPeriod` that's used to determine how many times to compound the funding rate when paying funding.

Right now the number of `updatePeriod` periods `n` that have elapsed since the last time a market was updated ends up dictating how many times to compound the funding rate i.e., calculating `(1-2*k)**n` (ignoring complications with existing queued positions).

With the additional UX benefits the [`historic-price`](https://github.com/overlay-market/overlay-v1-core/tree/historic-price) branch brings in settling positions, we can set our market's `updatePeriod` to as little as ~ 1 block's timespan. With a smaller `updatePeriod` though comes potentially larger values of `n` passed to [`FixedPoint.pow(FixedPoint.uq144x112 memory self, uint256 n)`](https://github.com/overlay-market/overlay-v1-core/blob/historic-price/contracts/libraries/FixedPoint.sol#L92) in our fixed point library, which calculates the power of the fixed point number recursively.

Paying funding out only every `compoundPeriod` vs every `updatePeriod` would allow us to pay funding less frequently (e.x. 10 min) and limit the recursions in the fixed point library's `FixedPoint.pow()` power calculation, while also allowing markets to be updated more frequently.

**Comment by mesozoic-technology** [comment]
If we separate the compounding period from the update period, what do we do for queued positions? do we decouple queuedOI from queued positions?

**Comment by mesozoic-technology** [comment]
Introducing a compounding period needs to introduce a metric by which a position's oi is known to be paid/paying funding or just queued oi. 

Accomplished by introducing the eligible compounding epoch onto the position struct.
